"""Cypress Test Generator — production-grade, webapp-agnostic.

Generated tests include:
  - Multi-strategy selectors with automatic fallback
  - Smart waits after navigation (cy.url().should('include', ...))
  - Configurable base URL via Cypress config or env var
  - Failure screenshots via Cypress built-in support
  - Overlay dismissal helpers
"""

from __future__ import annotations

import re
from typing import List, Optional
from urllib.parse import urlparse

from testai.models.journey import Journey
from testai.models.step import Step


_UUID_RE = re.compile(
    r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}", re.I
)
_NUMERIC_ID_RE = re.compile(r"/\d{4,}/")


def _relative_path(url: str) -> str:
    parsed = urlparse(url or "")
    return parsed.path or "/"


def _glob_path(path: str) -> str:
    path = _UUID_RE.sub("*", path)
    path = _NUMERIC_ID_RE.sub("/*/", path)
    return path


def _safe(text: str) -> str:
    return text.replace("'", "\\'").replace("\n", " ").strip()


def _cy_selector(step: Step) -> str:
    """Build the best Cypress selector for a step."""
    sel = step.selectors
    if not sel:
        hint = step.element_hint or step.description
        return f"cy.contains('{_safe(hint)}')"

    test_id = sel.get("test_id")
    if test_id:
        return f"cy.get('[data-testid=\"{_safe(test_id)}\"]')"

    aria = sel.get("aria_label")
    if aria:
        return f"cy.get('[aria-label=\"{_safe(aria)}\"]')"

    text = sel.get("text", "").strip()
    css = sel.get("css", "").strip()

    if text and css:
        return f"cy.get('{_safe(css)}').contains('{_safe(text)}')"
    if text:
        return f"cy.contains('{_safe(text)}')"
    if css:
        return f"cy.get('{_safe(css)}')"

    hint = step.element_hint or step.description
    return f"cy.contains('{_safe(hint)}')"


def _fill_value(step: Step) -> str:
    val = step.selectors.get("value", "") or ""
    if "password" in (step.element_hint or "").lower() or "password" in step.description.lower():
        return "Cypress.env('PASSWORD') || 'test_password'"
    if "email" in (step.element_hint or "").lower() or "email" in step.description.lower():
        return "Cypress.env('EMAIL') || 'test@example.com'"
    if "user" in (step.element_hint or "").lower():
        return "Cypress.env('USERNAME') || 'test_user'"
    return f"'{_safe(val)}'" if val else "'test_value'"


def _render(journey: Journey) -> str:
    steps = journey.steps
    if not steps:
        return "// No steps to export"

    origin = ""
    for s in steps:
        if s.url:
            parsed = urlparse(s.url)
            origin = f"{parsed.scheme}://{parsed.netloc}"
            break

    fn_name = re.sub(r"[^a-zA-Z0-9]+", " ", journey.name).strip().replace(" ", " ")
    conf = f"{journey.confidence * 100:.0f}%"

    lines = [
        f"// Auto-generated by Vigil — Cypress test with smart selectors.",
        f"// Journey: {journey.name} (confidence: {conf})",
        f"// Domain: {journey.domain} > {journey.feature}",
        f"//",
        f"// Run: npx cypress run --spec '{_cypress_filename(journey)}'",
        f"// Set base URL: CYPRESS_BASE_URL={origin or 'https://your-app.example.com'}",
        "",
        f"describe('{_safe(journey.name)}', () => {{",
        f"  beforeEach(() => {{",
        f"    cy.visit('/')",
        f"  }})",
        "",
        f"  it('{_safe(fn_name)}', () => {{",
    ]

    step_num = 0
    last_path = None

    for idx, step in enumerate(steps):
        desc = _safe(step.description)

        if step.action_type == "navigate":
            path = _relative_path(step.url)
            if path != last_path:
                step_num += 1
                lines.append("")
                lines.append(f"    // Step {step_num} — {desc}")
                glob = _glob_path(path)

                if idx > 0 and steps[idx - 1].action_type == "click":
                    lines.append(f"    cy.url().should('include', '{glob}')")
                else:
                    lines.append(f"    cy.visit('{path}')")

                last_path = path

        elif step.action_type == "click":
            step_num += 1
            sel = _cy_selector(step)
            lines.append("")
            lines.append(f"    // Step {step_num} — {desc}")
            lines.append(f"    {sel}.click()")

        elif step.action_type == "fill_form":
            step_num += 1
            sel = _cy_selector(step)
            val = _fill_value(step)
            lines.append("")
            lines.append(f"    // Step {step_num} — {desc}")
            lines.append(f"    {sel}.clear().type({val})")

        elif step.action_type == "submit":
            step_num += 1
            sel = _cy_selector(step)
            lines.append("")
            lines.append(f"    // Step {step_num} — {desc}")
            lines.append(f"    {sel}.submit()")

        elif step.action_type == "verify":
            step_num += 1
            text = step.selectors.get("text", "") or step.element_hint or ""
            aria = step.selectors.get("ariaLabel", "") or step.selectors.get("aria_label", "")
            css = step.selectors.get("css", "")
            lines.append("")
            lines.append(f"    // Step {step_num} — {desc}")
            if text:
                lines.append(f"    cy.contains('{_safe(text)}').should('be.visible')")
            elif aria:
                lines.append(f"    cy.get('[aria-label=\"{_safe(aria)}\"]').should('be.visible')")
            elif css:
                lines.append(f"    cy.get('{_safe(css)}').should('exist')")
            else:
                lines.append(f"    cy.url().should('not.be.empty') // verify page loaded")

        elif step.action_type == "dblclick":
            step_num += 1
            sel = _cy_selector(step)
            lines.append("")
            lines.append(f"    // Step {step_num} — {desc}")
            lines.append(f"    {sel}.dblclick()")

        elif step.action_type == "select":
            step_num += 1
            sel = _cy_selector(step)
            val = step.selectors.get("value", "")
            lines.append("")
            lines.append(f"    // Step {step_num} — {desc}")
            lines.append(f"    {sel}.select('{_safe(val)}')")

        elif step.action_type == "keypress":
            step_num += 1
            key = step.selectors.get("key", "Enter")
            lines.append("")
            lines.append(f"    // Step {step_num} — {desc}")
            lines.append(f"    cy.focused().type('{{{key}}}')")

        elif step.action_type == "keycombo":
            step_num += 1
            combo = step.selectors.get("combo", "")
            cy_combo = combo.replace("+", "{").replace("Ctrl", "ctrl").replace("Meta", "meta")
            lines.append("")
            lines.append(f"    // Step {step_num} — {desc}")
            lines.append(f"    cy.focused().type('{cy_combo}')")

        elif step.action_type in ("paste", "fill_form"):
            step_num += 1
            sel = _cy_selector(step)
            val = _fill_value(step)
            lines.append("")
            lines.append(f"    // Step {step_num} — {desc}")
            lines.append(f"    {sel}.clear().type({val})")

        else:
            step_num += 1
            lines.append("")
            lines.append(f"    // Step {step_num} — {desc} [{step.action_type}]")
            sel = _cy_selector(step)
            lines.append(f"    {sel}.should('exist')")

    lines.append("  })")
    lines.append("})")
    lines.append("")

    total = str(step_num)
    return "\n".join(lines).replace("{TOTAL}", total)


def _cypress_filename(journey: Journey) -> str:
    slug = re.sub(r"[^a-z0-9]+", "_", journey.name.lower()).strip("_")
    return f"cypress/e2e/{slug}.cy.js"


def _render_config(journey: Journey) -> str:
    origin = ""
    for s in journey.steps:
        if s.url:
            parsed = urlparse(s.url)
            origin = f"{parsed.scheme}://{parsed.netloc}"
            break

    return f"""// cypress.config.js — generated by Vigil
const {{ defineConfig }} = require('cypress')

module.exports = defineConfig({{
  e2e: {{
    baseUrl: '{origin or "http://localhost:3000"}',
    viewportWidth: 1280,
    viewportHeight: 720,
    defaultCommandTimeout: 10000,
    video: false,
    screenshotOnRunFailure: true,
  }},
}})
"""


class CypressExporter:
    def export(self, journey: Journey) -> str:
        return _render(journey)

    def export_config(self, journey: Journey) -> str:
        return _render_config(journey)

    def export_to_file(self, journey: Journey, output_path: str) -> str:
        content = self.export(journey)
        with open(output_path, "w") as f:
            f.write(content)
        return output_path
